NRC_GENERAL_REJECT = 0x10
NRC_SERVICE_NOT_SUPPORTED = 0x11
NRC_SUBFUNCTION_NOT_SUPPORTED = 0x12
NRC_INCORRECT_MESSAGE_LENGTH = 0x13

NRC_CONDITIONS_NOT_CORRECT = 0x22

NRC_REQUEST_OUT_OF_RANGE = 0x31
NRC_SECURITY_ACCESS_DENIED = 0x33

NRC_RESPONSE_PENDING = 0x78
NRC_SERVICE_NOT_SUPPORTED_IN_ACTIVE_SESSION = 0x7F

def create_negative_response(service_id: int, nrc: int):
    return bytearray([0x7F, service_id, nrc])