import secrets
import zlib
import simulator.main as main
import simulator.uds.negativeResponse as negative_response

def generate_seed() -> bytes:
    """
    Generates a cryptographically secure, random 4-byte seed.

    Returns:
        bytes: A securely generated 4-byte array sequence sent to the tester tool.
    """
    seed = secrets.token_bytes(4)
    print(seed.hex())
    return seed


def level1key(seed: bytes) -> bytes:
    """
    Computes the expected validation key for Security Level 1.

    Args:
        seed (bytes): The raw seed byte array generated by the server.

    Returns:
        bytes: The computed key using a bitwise XOR transformation mask (0xA5).
    """
    return bytes(b ^ 0xA5 for b in seed)


def level2key(seed: bytes) -> bytes:
    """
    Computes the expected validation key for Security Level 2.

    Applies an 8-bit left rotation by 3 bits on each byte, isolates the byte mask 
    boundary, and runs a fixed 0x5C bitwise XOR operation.

    Args:
        seed (bytes): The raw seed byte array generated by the server.

    Returns:
        bytes: The transformed deterministic expected validation key.
    """
    key = bytearray()
    for b in seed:
        rotated = ((b << 3) | (b >> 5)) & 0xFF
        key.append(rotated ^ 0x5C)
    return bytes(key)


def level3key(seed: bytes) -> bytes:
    """
    Computes the expected validation key for Security Level 3.

    Args:
        seed (bytes): The raw seed byte array generated by the server.

    Returns:
        bytes: A 4-byte big-endian representation of the seed's CRC32 checksum.
    """
    crc = zlib.crc32(seed)
    return crc.to_bytes(4, "big")


def handleSecurityAccess(payload: bytearray) -> bytearray:
    """
    Processes an incoming UDS SecurityAccess (Service 0x27) transaction frame.

    Implements the server-side state machine for the diagnostic seed-key exchange:
    - **Sub-function 0x00:** Locks or resets the active security level state back to 0.
    - **Odd Sub-functions (0x01, 0x03, 0x05):** Standard seed requests. Generates a secure, 
      random seed, computes the expected validation key for the requested level, caches 
      the key in global state (`main.security_key`), and returns the seed to the tester.
    - **Even Sub-functions (0x02, 0x04, 0x06):** Key validation submissions. Compares the 
      tester's submitted key with the cached internal key. Unlocks the session on success, 
      or returns an explicit Security Access Denied error on a mismatch.

    Args:
        payload (bytearray): Raw incoming request buffer containing `[SID][Sub-Function][Optional Key Payload]`.

    Returns:
        bytearray: A finalized response buffer containing either a positive response matrix 
                   mirroring the transaction sub-functions, or a structured Negative Response.
    """
    req = payload[1]
    print("inside handle security")
    
    # Condition 1: Drop or check the active security privileges back to level 0
    if req == 0:
        main.security_level = 0
        response = bytearray([payload[0] + 0x40])  # Positive Response SID (0x27 + 0x40 = 0x67)
        response.append(payload[1])
        
    # Condition 2: Step 1 of Handshake — Requesting a Seed (Odd Sub-functions)
    elif req % 2 == 1:
        seed = generate_seed()
        response = bytearray([0x67])  # Positive Response SID
        response.append(req)
        response.extend(seed)

        # Pre-calculate and cache the reference key matching the requested tier
        if payload[1] == 0x01:
            main.security_key = level1key(seed)
            main.security_level = 1
        elif payload[1] == 0x03:
            main.security_key = level2key(seed)
            main.security_level = 2
        elif payload[1] == 0x05:
            main.security_key = level3key(seed)
            main.security_level = 3
            
    # Condition 3: Step 2 of Handshake — Verifying Submited Key (Even Sub-functions)
    else:
        tester_key = payload[2:]
        print("Verifying key...")

        # Securely compare the client's submitted key against the cached value
        if tester_key == main.security_key:
            response = bytearray([payload[0] + 0x40])  # Positive Response SID (0x67)
            response.append(payload[1])
            print("Unlocked successfully")
            # Note: The actual upgrade of operational state privileges happens safely here 
            # upon successful validation, rather than early during the seed generation step.
        else:
            response = negative_response.create_negative_response(
                payload[0], 
                negative_response.NRC_SECURITY_ACCESS_DENIED
            )
            print("Keys did not match")
            print("tester_key   : ", tester_key)
            print("security_key : ", main.security_key)

    return response