from threading import Lock
from utils.frontendFieldMapper import build_analytics_packet
import logger.logger as logger
import listener.listener as listener
from uds_client.uds_client import UDS, UDSRoles
import Decoder.decoder_thread as decoder
import isotp
from uds_client.UDSError import UDSError
from utils.files import zip_folder
from utils.updateHistory import history, update_history
from flask import Flask, request, jsonify, render_template, send_file
from dids.didList import DID_NAMES
import os
import logging
import time
import json

# Thread-safe global variables caching real-time network layer telemetry parameters
latest_analytics = {}
analytics_lock = Lock()
uds_client: UDS

# Application session context tracking states
current_session = 1
current_security_level = 0

# Initialize Flask application with targeted routing markers pointing to template resources
app = Flask(
    __name__,
    template_folder="Frontend/templates",
    static_folder="Frontend/static"
)

# Operational profiling flags tracking performance indices (e.g., messages per second)
start_time_flag: float = 0
prev_count: int = 0

class RouteFilter(logging.Filter):
    """
    Custom logging filter used to clean up engine stdout lines.
    
    Suppresses recurring log entries generated by high-frequency background polling 
    on the `/live-data` endpoint, keeping the core system console clear.
    """
    def filter(self, record: logging.LogRecord) -> bool:
        msg = record.getMessage()
        if "GET /live-data" in msg:
            return False
        return True

# Apply the filter directly to the underlying Werkzeug server engine logger
werkzeug_logger = logging.getLogger("werkzeug")
werkzeug_logger.addFilter(RouteFilter())


@app.route("/")
def home():
    """
    Renders the principal GUI dashboard layout index page.

    As an initialization step, it resets the remote ECU back to the default diagnostic 
    session and drops active security access metrics back to basic tiers.
    """
    try:
        uds_client.diagnostic_session_control(1)
        uds_client.security_access(0)
        return render_template('index.html')
    except Exception as e:
        print(e)
        return jsonify({
            "status": "error",
            "message": "Session Access Failed"
        })
    
@app.route("/DID",methods=["GET"])
def get_all_DID():
    return jsonify(
        DID_NAMES
        )
@app.route("/DID/<int:DID>", methods=["GET"])
def get_DID(DID: int):
    """
    Fetches the value of a specific Data Identifier (DID) via UDS Service 0x22.

    Args:
        DID (int): The 16-bit identifier index parameter requested by the client interface.
    """
    if uds_client is None: 
        return jsonify({
            "status": "error",
            "message": "UDS client not initialized"
        })
    try:
        response = uds_client.readDataByIdentifier(DID)
        return jsonify({
            "status": "success",
            "data": response 
        })
    except UDSError as e:
        print(e)
        return jsonify({
            "status": "error",
            "message": e.message
        })


@app.route("/DID", methods=["POST"])
def set_DID():
    """Modifies a specific Data Identifier (DID) value via UDS Service 0x2E."""
    data = request.get_json()
    print(data.get("DID"), data.get("value"))
    if uds_client is None: 
        return jsonify({
            "status": "error",
            "message": "UDS client not initialized"
        })
    try:
        response = uds_client.writeDataByIdentifier(data.get("DID"), data.get("value"))
        return jsonify(response)
    except Exception as e:
        print(e)
        return jsonify({
            "status": "error",
            "data": "Data could not be written"
        })


@app.route("/DTC", methods=["GET"])
def get_all_DTC():
    """Queries and streams all active/confirmed Diagnostic Trouble Codes via UDS Service 0x19."""
    try:
        response = uds_client.read_dtcs()
        return jsonify(response)
    except UDSError as e:
        print(e)
        return jsonify({
            "status": "error",
            "message": e.message
        })


@app.route("/DTC", methods=["DELETE"])
def clearDTC():
    """Clears all logged Diagnostic Trouble Codes via UDS Service 0x14."""
    try:
        response = uds_client.clear_all_dtcs()
        return jsonify(response)
    except UDSError as e:
        print(e)
        return jsonify({
            "status": "error",
            "message": e.message
        })
    

@app.route("/download/<file>")
def download(file: str):
    """
    Coordinates filesystem archiving and dynamic data dumping operations.

    Handles compressed log extractions or coordinates safe local storage dump mappings 
    by invoking high-level diagnostic firmware download tools before passing the files down 
    the response pipeline. Uses resource cleanup handles upon closing the stream.

    Args:
        file (str): Categorized download token ("logger" or "firmware").
    """
    if file == "logger":
        print("sending logger...")
        zip_folder("../data/logger", "../data/all_logs")
        print("zip created!!")
       
        path = os.path.dirname(os.getcwd())
        path = os.path.join(path, 'data', 'all_logs.zip')
        response = send_file(path, as_attachment=True, conditional=False)
        response.direct_passthrough = False
        
        # Async Lifecycle Cleanup Hook: Erase the temporary zip archive once the client finishes downloading it
        @response.call_on_close
        def cleanup():
            try:
                os.remove(path)
                print("Zip deleted.")
            except Exception as e:
                print(f"Cleanup failed: {e}")
        return response
    
    if file == "firmware":
        path = os.path.join(os.path.dirname(os.getcwd()), 'data', 'firmware', 'firmware.bin')
        try:
            # Command the UDS client engine to read firmware blocks sequentially from the flash memory lines
            uds_client.firmwareUpload(path)
            response = send_file(path, as_attachment=True, conditional=False)
            response.direct_passthrough = False

            @response.call_on_close
            def cleanup():
                try:
                    os.remove(path)
                    print("firmware duplicate deleted.")
                except Exception as e:
                    print(f"Cleanup failed: {e}")
            return response
        except UDSError as e:
            print(e)
            return jsonify({
                "status": "error",
                "message": e.message
            })
        except Exception as e:
            print(e)
            return jsonify({
                "status": "error",
                "message": "Could not download firmware"
            })


@app.route("/security_access/<int:level>")
def security_access(level: int):
    """
    Requests a diagnostic session security level unlock via UDS Service 0x27.

    Args:
        level (int): Target authentication tier requested from the node ecosystem.
    """
    try:
        uds_client.security_access(level)
        return jsonify({
            "status": "success",
            "message": "Security Access Granted"
        })
    except Exception as e:
        print(e)
        return jsonify({
            "status": "error",
            "message": "Security Access Failed"
        })


@app.route("/diagnostics_session_control/<int:session>")
def diagnostics_session_control(session: int):
    """
    Transitions the target ECU between diagnostic sessions via UDS Service 0x10.

    Args:
        session (int): Target session type (e.g., 0x01 Default, 0x02 Programming, 0x03 Extended).
    """
    try:
        uds_client.diagnostic_session_control(session)
        return jsonify({
            "status": "success",
            "message": "Session Access Granted"
        })
    except Exception as e:
        print(e)
        return jsonify({
            "status": "error",
            "message": "Session Access Failed"
        })


@app.route("/IO_control", methods=["POST"])
def IO_control():
    """Executes signal manual overrides or returns device control to the ECU via UDS Service 0x2F."""
    data = request.get_json()
    print(f"DID : {data.get('DID')}. type: {type(data.get('DID'))}")
    print(f"control parameter: {data.get('control_parameter')}. type: {type(data.get('control_parameter'))}")
    print(f"control state : {data.get('control_state')}. type: {type(data.get('control_state'))}")

    try:
        uds_client.io_control(data.get('DID'), data.get('control_parameter'), data.get('control_state'))
        return jsonify({
            "status": "success",
            "message": "Control changed"
        })
    except UDSError as e:
        print("UDS Error\n", e)
        return jsonify({
            "status": "error",
            "message": e.message
        })
    except Exception as e:
        print(e)
        return jsonify({
            "status": "error",
            "message": "Could not change control"
        })


@app.route("/live-data", methods=["GET"])
def live_data():
    """
    Scrapes high-frequency system telemetry parameters.

    Calculates current transport indices such as message processing speeds (frames per second) 
    and updates error metrics before compiling them into a JSON map response.
    """
    stats = listener.get_stats()
    with analytics_lock:
        global start_time_flag
        global prev_count
        
        latest_analytics["error_frames"] = stats.error_frames
        
        # Calculate localized performance metrics: (Current Frames - Past Frames) / Elapsed Seconds
        delta_time = time.monotonic() - start_time_flag
        latest_analytics["message_speed"] = round((stats.rx_frames - prev_count) / delta_time, 2)
        
        # Sync baseline parameters for the next polling cycle
        prev_count = stats.rx_frames
        start_time_flag = time.monotonic()
        
        return jsonify(latest_analytics)


def send_realtime_data(frame):
    """
    Pipes processed asynchronous network data into web thread caches.

    This callback function updates history buffers and current analytics metrics 
    every time the decoder thread extracts a fresh payload frame from the CAN bus.

    Args:
        frame (CANFrame): Normalized network frame object data.
    """
    analytics = build_analytics_packet(frame)

    with analytics_lock:
        update_history(analytics)
        latest_analytics.update(analytics)


@app.route("/history-data", methods=["GET"])
def history_data():
    """Streams the accumulated chronological historical database records compiled during this session."""
    with analytics_lock:
        history_json = json.dumps(
            {key: list(value) for key, value in history.items()},
            indent=4
        )
        return history_json


@app.route("/state", methods=["GET"])
def get_state():
    """Returns the internal state variables tracking the active user's session tier and access credentials."""
    return {
        "status": "success",
        "current_session": current_session,
        "current_security_level": current_security_level
    }


if __name__ == "__main__":
    # Initialize the 11-bit Normal Addressing transport layers for the local ISO-TP engine wrapper
    address = isotp.Address(
        isotp.AddressingMode.Normal_11bits,
        txid=0x22,
        rxid=0x62
    )
    
    # Bootstrap the unified client model tracking standard basic authorizations
    uds_client = UDS(UDSRoles.USER)
    
    # Spin up background async notifier frameworks and thread worker contexts
    listener.start(address, uds_client.on_response, channel="vcan0")
    start_time_flag = time.monotonic()
    
    decoder.start(send_realtime_data)
    logger.start()
    
    # Initialize the Flask web API gateway listening on the host interface loopback
    app.run()